import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Plus, Edit, Trash2 } from 'lucide-react';
import { useAppContext } from '@/context/PlayerContext';
import { ContactRole } from '@/types';

const ManageRoles = () => {
  const navigate = useNavigate();
  const { contactRoles, addContactRole, updateContactRole, deleteContactRole } = useAppContext();

  // Contact Role Management
  const [isContactRoleDialogOpen, setIsContactRoleDialogOpen] = useState(false);
  const [editingRole, setEditingRole] = useState<ContactRole | null>(null);
  const [roleName, setRoleName] = useState('');
  const [roleDescription, setRoleDescription] = useState('');

  // Contact Role Management Functions
  const handleAddContactRole = () => {
    setEditingRole(null);
    setRoleName('');
    setRoleDescription('');
    setIsContactRoleDialogOpen(true);
  };

  const handleEditContactRole = (role: ContactRole) => {
    setEditingRole(role);
    setRoleName(role.roleName);
    setRoleDescription(role.description || '');
    setIsContactRoleDialogOpen(true);
  };

  const handleSaveContactRole = async () => {
    if (!roleName.trim()) return;

    try {
      if (editingRole) {
        // Update existing role
        await updateContactRole({
          ...editingRole,
          roleName: roleName.trim(),
          description: roleDescription.trim()
        });
      } else {
        // Create new role
        await addContactRole({
          roleId: '', // Will be generated by backend
          roleName: roleName.trim(),
          description: roleDescription.trim(),
          createdAt: new Date().toISOString(),
          createdBy: 'admin' // TODO: Get from auth context
        });
      }
      setIsContactRoleDialogOpen(false);
      setRoleName('');
      setRoleDescription('');
      setEditingRole(null);
    } catch (err) {
      console.error('Error saving contact role:', err);
    }
  };

  const handleDeleteContactRole = async (roleId: string) => {
    try {
      await deleteContactRole(roleId);
    } catch (err) {
      console.error('Error deleting contact role:', err);
    }
  };

  return (
    <div className="max-w-5xl mx-auto py-6">
      <Card className="shadow-lg border rounded-2xl">
        <CardHeader className="border-b pb-4">
          <CardTitle className="text-2xl font-semibold">👥 Manage Roles</CardTitle>
          <p className="text-muted-foreground">Manage contact roles for club contacts and staff members.</p>
        </CardHeader>

        <CardContent className="space-y-6 pt-6">
          {/* ================= CONTACT ROLES MANAGEMENT ================= */}
          <div>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">Contact Roles</h2>
              <Dialog open={isContactRoleDialogOpen} onOpenChange={setIsContactRoleDialogOpen}>
                <DialogTrigger asChild>
                  <Button onClick={handleAddContactRole} size="sm">
                    <Plus className="w-4 h-4 mr-2" />
                    Add Role
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>{editingRole ? 'Edit Contact Role' : 'Add Contact Role'}</DialogTitle>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="roleName">Role Name *</Label>
                      <Input
                        id="roleName"
                        value={roleName}
                        onChange={(e) => setRoleName(e.target.value)}
                        placeholder="e.g., President, Coach, Manager"
                      />
                    </div>
                    <div>
                      <Label htmlFor="roleDescription">Description</Label>
                      <Textarea
                        id="roleDescription"
                        value={roleDescription}
                        onChange={(e) => setRoleDescription(e.target.value)}
                        placeholder="Optional description of the role"
                        rows={3}
                      />
                    </div>
                    <div className="flex justify-end gap-2">
                      <Button variant="outline" onClick={() => setIsContactRoleDialogOpen(false)}>
                        Cancel
                      </Button>
                      <Button onClick={handleSaveContactRole} disabled={!roleName.trim()}>
                        {editingRole ? 'Update' : 'Create'} Role
                      </Button>
                    </div>
                  </div>
                </DialogContent>
              </Dialog>
            </div>

            <div className="border rounded-lg">
              <div className="p-4">
                {contactRoles.length === 0 ? (
                  <p className="text-muted-foreground text-center py-8">
                    No contact roles defined yet. Click "Add Role" to create your first contact role.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {contactRoles.map((role) => (
                      <div key={role.roleId} className="flex items-center justify-between p-3 border rounded-md bg-muted/20">
                        <div className="flex-1">
                          <div className="font-medium">{role.roleName}</div>
                          {role.description && (
                            <div className="text-sm text-muted-foreground mt-1">{role.description}</div>
                          )}
                        </div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleEditContactRole(role)}
                          >
                            <Edit className="w-4 h-4" />
                          </Button>
                          <AlertDialog>
                            <AlertDialogTrigger asChild>
                              <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive">
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </AlertDialogTrigger>
                            <AlertDialogContent>
                              <AlertDialogHeader>
                                <AlertDialogTitle>Delete Contact Role</AlertDialogTitle>
                                <AlertDialogDescription>
                                  Are you sure you want to delete the "{role.roleName}" role? This action cannot be undone and may affect existing club contacts using this role.
                                </AlertDialogDescription>
                              </AlertDialogHeader>
                              <AlertDialogFooter>
                                <AlertDialogCancel>Cancel</AlertDialogCancel>
                                <AlertDialogAction
                                  onClick={() => handleDeleteContactRole(role.roleId)}
                                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                                >
                                  Delete
                                </AlertDialogAction>
                              </AlertDialogFooter>
                            </AlertDialogContent>
                          </AlertDialog>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* ================= ACTIONS ================= */}
          <div className="flex justify-end gap-3 pt-4 border-t">
            <Button variant="outline" onClick={() => navigate(-1)}>Back</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ManageRoles;