import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Plus, Edit, Trash2 } from 'lucide-react';
import { useAppContext } from '@/context/PlayerContext';
import { PlayerPosition } from '@/types';

const ManagePositions = () => {
  const navigate = useNavigate();
  const { playerPositions, addPlayerPosition, updatePlayerPosition, deletePlayerPosition } = useAppContext();

  // Player Position Management
  const [isPlayerPositionDialogOpen, setIsPlayerPositionDialogOpen] = useState(false);
  const [editingPosition, setEditingPosition] = useState<PlayerPosition | null>(null);
  const [positionCode, setPositionCode] = useState('');
  const [positionName, setPositionName] = useState('');
  const [positionDescription, setPositionDescription] = useState('');

  // Player Position Management Functions
  const handleAddPlayerPosition = () => {
    setEditingPosition(null);
    setPositionCode('');
    setPositionName('');
    setPositionDescription('');
    setIsPlayerPositionDialogOpen(true);
  };

  const handleEditPlayerPosition = (position: PlayerPosition) => {
    setEditingPosition(position);
    setPositionCode(position.positionCode);
    setPositionName(position.positionName);
    setPositionDescription(position.description || '');
    setIsPlayerPositionDialogOpen(true);
  };

  const handleSavePlayerPosition = async () => {
    if (!positionCode.trim() || !positionName.trim()) return;

    try {
      if (editingPosition) {
        // Update existing position
        await updatePlayerPosition({
          ...editingPosition,
          positionCode: positionCode.trim(),
          positionName: positionName.trim(),
          description: positionDescription.trim()
        });
      } else {
        // Create new position
        await addPlayerPosition({
          positionId: '', // Will be generated by backend
          positionCode: positionCode.trim(),
          positionName: positionName.trim(),
          description: positionDescription.trim(),
          createdAt: new Date().toISOString(),
          createdBy: 'admin' // TODO: Get from auth context
        });
      }
      setIsPlayerPositionDialogOpen(false);
      setPositionCode('');
      setPositionName('');
      setPositionDescription('');
      setEditingPosition(null);
    } catch (err) {
      console.error('Error saving player position:', err);
    }
  };

  const handleDeletePlayerPosition = async (positionId: string) => {
    try {
      await deletePlayerPosition(positionId);
    } catch (err) {
      console.error('Error deleting player position:', err);
    }
  };

  return (
    <div className="max-w-5xl mx-auto py-6">
      <Card className="shadow-lg border rounded-2xl">
        <CardHeader className="border-b pb-4">
          <CardTitle className="text-2xl font-semibold">⚽ Manage Positions</CardTitle>
          <p className="text-muted-foreground">Manage player positions for the scouting system.</p>
        </CardHeader>

        <CardContent className="space-y-6 pt-6">
          {/* ================= PLAYER POSITIONS MANAGEMENT ================= */}
          <div>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">Player Positions</h2>
              <Dialog open={isPlayerPositionDialogOpen} onOpenChange={setIsPlayerPositionDialogOpen}>
                <DialogTrigger asChild>
                  <Button onClick={handleAddPlayerPosition} size="sm">
                    <Plus className="w-4 h-4 mr-2" />
                    Add Position
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>{editingPosition ? 'Edit Player Position' : 'Add Player Position'}</DialogTitle>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="positionCode">Position Code *</Label>
                      <Input
                        id="positionCode"
                        value={positionCode}
                        onChange={(e) => setPositionCode(e.target.value)}
                        placeholder="e.g., GK, CB, ST"
                      />
                    </div>
                    <div>
                      <Label htmlFor="positionName">Position Name *</Label>
                      <Input
                        id="positionName"
                        value={positionName}
                        onChange={(e) => setPositionName(e.target.value)}
                        placeholder="e.g., Goalkeeper, Centre Back, Striker"
                      />
                    </div>
                    <div>
                      <Label htmlFor="positionDescription">Description</Label>
                      <Textarea
                        id="positionDescription"
                        value={positionDescription}
                        onChange={(e) => setPositionDescription(e.target.value)}
                        placeholder="Optional description of the position"
                        rows={3}
                      />
                    </div>
                    <div className="flex justify-end gap-2">
                      <Button variant="outline" onClick={() => setIsPlayerPositionDialogOpen(false)}>
                        Cancel
                      </Button>
                      <Button onClick={handleSavePlayerPosition} disabled={!positionCode.trim() || !positionName.trim()}>
                        {editingPosition ? 'Update' : 'Create'} Position
                      </Button>
                    </div>
                  </div>
                </DialogContent>
              </Dialog>
            </div>

            <div className="border rounded-lg">
              <div className="p-4">
                {playerPositions.length === 0 ? (
                  <p className="text-muted-foreground text-center py-8">
                    No player positions defined yet. Click "Add Position" to create your first player position.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {playerPositions.map((position) => (
                      <div key={position.positionId} className="flex items-center justify-between p-3 border rounded-md bg-muted/20">
                        <div className="flex-1">
                          <div className="font-medium">
                            <span className="font-mono bg-muted px-2 py-1 rounded text-sm mr-2">{position.positionCode}</span>
                            {position.positionName}
                          </div>
                          {position.description && (
                            <div className="text-sm text-muted-foreground mt-1">{position.description}</div>
                          )}
                        </div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleEditPlayerPosition(position)}
                          >
                            <Edit className="w-4 h-4" />
                          </Button>
                          <AlertDialog>
                            <AlertDialogTrigger asChild>
                              <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive">
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </AlertDialogTrigger>
                            <AlertDialogContent>
                              <AlertDialogHeader>
                                <AlertDialogTitle>Delete Player Position</AlertDialogTitle>
                                <AlertDialogDescription>
                                  Are you sure you want to delete the "{position.positionName}" position? This action cannot be undone and may affect existing players using this position.
                                </AlertDialogDescription>
                              </AlertDialogHeader>
                              <AlertDialogFooter>
                                <AlertDialogCancel>Cancel</AlertDialogCancel>
                                <AlertDialogAction
                                  onClick={() => handleDeletePlayerPosition(position.positionId)}
                                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                                >
                                  Delete
                                </AlertDialogAction>
                              </AlertDialogFooter>
                            </AlertDialogContent>
                          </AlertDialog>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* ================= ACTIONS ================= */}
          <div className="flex justify-end gap-3 pt-4 border-t">
            <Button variant="outline" onClick={() => navigate(-1)}>Back</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ManagePositions;